services:
  frontend:
    build:
      context: ./organizo-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      VITE_API_URL: "http://app:8080/api"
    depends_on:
      - app
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: organizo
      MYSQL_USER: organizo
      MYSQL_PASSWORD: organizo_pass
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:6-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/organizo?useUnicode=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: organizo
      SPRING_DATASOURCE_PASSWORD: organizo_pass
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_MAIL_HOST: sandbox.smtp.mailtrap.io
      SPRING_MAIL_PORT: 2525
      SPRING_MAIL_USERNAME: a4ba6720f4eb7b
      SPRING_MAIL_PASSWORD: fe5579309a75ca
    depends_on:
      - mysql
      - redis

volumes:
  mysql-data:
