spring:
  datasource:
    # se não vier SPRING_DATASOURCE_URL do ambiente, usa o localhost (útil para rodar direto no IntelliJ)
    url:      ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/organizo?useUnicode=true&serverTimezone=America/Sao_Paulo}
    # padrão 'organizo' (atualize se você tiver outro usuário)
    username: ${SPRING_DATASOURCE_USERNAME:organizo}
    # agora com fallback para 'organizo_pass'
    password: ${SPRING_DATASOURCE_PASSWORD:organizo_pass}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth
          jwk-set-uri: http://localhost:8080/auth/.well-known/jwks.json

  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}
    cache:
      type: redis

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: a4ba6720f4eb7b
    password: fe5579309a75ca
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.springframework: DEBUG

jwt:
  secret: ${JWT_SECRET:umaChaveMuitoSecreta1234567890}
  expiration: 3600000  # 1h em milissegundos

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus