spring:
  datasource:
    url: jdbc:mysql://localhost:3306/organizo?useUnicode=true&serverTimezone=America/Sao_Paulo
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: a4ba6720f4eb7b
    password: fe5579309a75ca
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.springframework: DEBUG